Repository Soviet-Linux/CCCP, pull requests merged in 2023-11, with the labels that each got.

#27 added stuff
  src/main.c
Labels: size/S

#28 added stuff
  src/main.c
Labels: size/S

#29 forfor
  src/main.c
Labels: size/S

#30 add bin foldr to .gitignore
  .gitignore
Labels: size/XS

#31 added support for search
  src/main.c
Labels: size/XS

#33 better commends
  src/main.c
Labels: size/S

#34 fix error from codefactor
  Dockerfile
Labels: size/XS

#36 Fixed Makefile
  Makefile
Labels: size/S

#37 Added uninstall command on the Makefile and added short versions of CCCP commands
  Makefile
  src/main.c
Labels: size/M

#39 Fix echo
  Makefile
  cccp.conf
Labels: size/XS
