Repository Soviet-Linux/CCCP, pull requests merged in 2023-10, with the labels that each got.

#7 Removed Unessesary print and added codefactor rating
  Makefile
  readme.md
  src/main.c
Labels: size/S

#8 Update readme.md
  readme.md
Labels: size/XS

#9 Create codeql.yml
  .github/workflows/codeql.yml
Labels: size/M

#10 added a dockerfile
  dockerfile
Labels: size/M

#11 Create docker-publish.yml
  .github/workflows/docker-publish.yml
Labels: size/M

#13 fixed docker image
  Dockerfile
Labels: size/XS

#15 create cccp.conf on sudo make install
  Makefile
Labels: size/XS

#16 Update Dockerfile
  Dockerfile
Labels: size/XS

#17 make main.c more readable
  src/main.c
Labels: size/XS

#19 Fixed if statements in main.c
  src/main.c
Labels: size/S

#20 Update main.c
  src/main.c
Labels: size/XS

#21 remove sudo
  Makefile
Labels: size/XS

#22 Update Makefile
  Makefile
Labels: size/XS

#23 cccp config
  Makefile
Labels: size/XS

#25 expanded the help menu
  src/main.c
Labels: size/M

#26 Make search, update and list return 0
  src/main.c
Labels: size/XS
